'use strict';

var fs        = require('fs')
  , json      = fs.readFileSync('./countries.json')
  , countries = JSON.parse(json)
;

var data = {};

data.country = {
  "af": {"latitude": 33, "longitude": 65, "continent": "Africa"},
  "al": {"latitude": 41, "longitude": 20, "continent": "Europe"},
  "aq": {"latitude": -90, "longitude": 0, "continent": "Antarctica"},
  "dz": {"latitude": 28, "longitude": 3, "continent": "Africa"},
  "as": {"latitude": -14.3333, "longitude": -170, "continent": "Oceania"},
  "ad": {"latitude": 42.5, "longitude": 1.5, "continent": "Europe"},
  "ao": {"latitude": -12.5, "longitude": 18.5, "continent": "Africa"},
  "ag": {"latitude": 17.05, "longitude": -61.8, "continent": "North America"},
  "az": {"latitude": 40.5, "longitude": 47.5, "continent": "Africa"},
  "ar": {"latitude": -34, "longitude": -64, "continent": "South America"},
  "au": {"latitude": -27, "longitude": 133, "continent": "Oceania"},
  "at": {"latitude": 47.3333, "longitude": 13.3333, "continent": "Europe"},
  "bs": {"latitude": 24.25, "longitude": -76, "continent": "North America"},
  "bh": {"latitude": 26, "longitude": 50.55, "continent": "Africa"},
  "bd": {"latitude": 24, "longitude": 90, "continent": "Africa"},
  "am": {"latitude": 40, "longitude": 45, "continent": "Africa"},
  "bb": {"latitude": 13.1667, "longitude": -59.5333, "continent": "North America"},
  "be": {"latitude": 50.8333, "longitude": 4, "continent": "Europe"},
  "bm": {"latitude": 32.3333, "longitude": -64.75, "continent": "North America"},
  "bt": {"latitude": 27.5, "longitude": 90.5, "continent": "Africa"},
  "bo": {"latitude": -17, "longitude": -65, "continent": "South America"},
  "ba": {"latitude": 44, "longitude": 18, "continent": "Europe"},
  "bw": {"latitude": -22, "longitude": 24, "continent": "Africa"},
  "bv": {"latitude": -54.4333, "longitude": 3.4, "continent": "Antarctica"},
  "br": {"latitude": -10, "longitude": -55, "continent": "South America"},
  "bz": {"latitude": 17.25, "longitude": -88.75, "continent": "North America"},
  "io": {"latitude": -6, "longitude": 71.5, "continent": "Africa"},
  "sb": {"latitude": -8, "longitude": 159, "continent": "Oceania"},
  "vg": {"latitude": 18.5, "longitude": -64.5, "continent": "North America"},
  "bn": {"latitude": 4.5, "longitude": 114.6667, "continent": "Africa"},
  "bg": {"latitude": 43, "longitude": 25, "continent": "Europe"},
  "mm": {"latitude": 22, "longitude": 98, "continent": "Africa"},
  "bi": {"latitude": -3.5, "longitude": 30, "continent": "Africa"},
  "by": {"latitude": 53, "longitude": 28, "continent": "Europe"},
  "kh": {"latitude": 13, "longitude": 105, "continent": "Africa"},
  "cm": {"latitude": 6, "longitude": 12, "continent": "Africa"},
  "ca": {"latitude": 60, "longitude": -95, "continent": "North America"},
  "cv": {"latitude": 16, "longitude": -24, "continent": "Africa"},
  "ky": {"latitude": 19.5, "longitude": -80.5, "continent": "North America"},
  "cf": {"latitude": 7, "longitude": 21, "continent": "Africa"},
  "lk": {"latitude": 7, "longitude": 81, "continent": "Africa"},
  "td": {"latitude": 15, "longitude": 19, "continent": "Africa"},
  "cl": {"latitude": -30, "longitude": -71, "continent": "South America"},
  "cn": {"latitude": 35, "longitude": 105, "continent": "Africa"},
  "tw": {"latitude": 23.5, "longitude": 121, "continent": "Africa"},
  "cx": {"latitude": -10.5, "longitude": 105.6667, "continent": "Africa"},
  "cc": {"latitude": -12.5, "longitude": 96.8333, "continent": "Africa"},
  "co": {"latitude": 4, "longitude": -72, "continent": "South America"},
  "km": {"latitude": -12.1667, "longitude": 44.25, "continent": "Africa"},
  "yt": {"latitude": -12.8333, "longitude": 45.1667, "continent": "Africa"},
  "cg": {"latitude": -1, "longitude": 15, "continent": "Africa"},
  "cd": {"latitude": 0, "longitude": 25, "continent": "Africa"},
  "ck": {"latitude": -21.2333, "longitude": -159.7667, "continent": "Oceania"},
  "cr": {"latitude": 10, "longitude": -84, "continent": "North America"},
  "hr": {"latitude": 45.1667, "longitude": 15.5, "continent": "Europe"},
  "cu": {"latitude": 21.5, "longitude": -80, "continent": "North America"},
  "cy": {"latitude": 35, "longitude": 33, "continent": "Africa"},
  "cz": {"latitude": 49.75, "longitude": 15.5, "continent": "Europe"},
  "bj": {"latitude": 9.5, "longitude": 2.25, "continent": "Africa"},
  "dk": {"latitude": 56, "longitude": 10, "continent": "Europe"},
  "dm": {"latitude": 15.4167, "longitude": -61.3333, "continent": "North America"},
  "do": {"latitude": 19, "longitude": -70.6667, "continent": "North America"},
  "ec": {"latitude": -2, "longitude": -77.5, "continent": "South America"},
  "sv": {"latitude": 13.8333, "longitude": -88.9167, "continent": "North America"},
  "gq": {"latitude": 2, "longitude": 10, "continent": "Africa"},
  "et": {"latitude": 8, "longitude": 38, "continent": "Africa"},
  "er": {"latitude": 15, "longitude": 39, "continent": "Africa"},
  "ee": {"latitude": 59, "longitude": 26, "continent": "Europe"},
  "fo": {"latitude": 62, "longitude": -7, "continent": "Europe"},
  "fk": {"latitude": -51.75, "longitude": -59, "continent": "South America"},
  "gs": {"latitude": -54.5, "longitude": -37, "continent": "Antarctica"},
  "fj": {"latitude": -18, "longitude": 175, "continent": "Oceania"},
  "fi": {"latitude": 64, "longitude": 26, "continent": "Europe"},
  "ax": {"latitude": 60.15, "longitude": 20, "continent": "Europe"},
  "fr": {"latitude": 46, "longitude": 2, "continent": "Europe"},
  "gf": {"latitude": 4, "longitude": -53, "continent": "South America"},
  "pf": {"latitude": -15, "longitude": -140, "continent": "Oceania"},
  "tf": {"latitude": -43, "longitude": 67, "continent": "Antarctica"},
  "dj": {"latitude": 11.5, "longitude": 43, "continent": "Africa"},
  "ga": {"latitude": -1, "longitude": 11.75, "continent": "Africa"},
  "ge": {"latitude": 42, "longitude": 43.5, "continent": "Africa"},
  "gm": {"latitude": 13.4667, "longitude": -16.5667, "continent": "Africa"},
  "ps": {"latitude": 32, "longitude": 35.25, "continent": "Africa"},
  "de": {"latitude": 51, "longitude": 9, "continent": "Europe"},
  "gh": {"latitude": 8, "longitude": -2, "continent": "Africa"},
  "gi": {"latitude": 36.1833, "longitude": -5.3667, "continent": "Europe"},
  "ki": {"latitude": 1.4167, "longitude": 173, "continent": "Oceania"},
  "gr": {"latitude": 39, "longitude": 22, "continent": "Europe"},
  "gl": {"latitude": 72, "longitude": -40, "continent": "North America"},
  "gd": {"latitude": 12.1167, "longitude": -61.6667, "continent": "North America"},
  "gp": {"latitude": 16.25, "longitude": -61.5833, "continent": "North America"},
  "gu": {"latitude": 13.4667, "longitude": 144.7833, "continent": "Oceania"},
  "gt": {"latitude": 15.5, "longitude": -90.25, "continent": "North America"},
  "gn": {"latitude": 11, "longitude": -10, "continent": "Africa"},
  "gy": {"latitude": 5, "longitude": -59, "continent": "South America"},
  "ht": {"latitude": 19, "longitude": -72.4167, "continent": "North America"},
  "hm": {"latitude": -53.1, "longitude": 72.5167, "continent": "Antarctica"},
  "va": {"latitude": 41.9, "longitude": 12.45, "continent": "Europe"},
  "hn": {"latitude": 15, "longitude": -86.5, "continent": "North America"},
  "hk": {"latitude": 22.25, "longitude": 114.1667, "continent": "Africa"},
  "hu": {"latitude": 47, "longitude": 20, "continent": "Europe"},
  "is": {"latitude": 65, "longitude": -18, "continent": "Europe"},
  "in": {"latitude": 20, "longitude": 77, "continent": "Africa"},
  "id": {"latitude": -5, "longitude": 120, "continent": "Africa"},
  "ir": {"latitude": 32, "longitude": 53, "continent": "Africa"},
  "iq": {"latitude": 33, "longitude": 44, "continent": "Africa"},
  "ie": {"latitude": 53, "longitude": -8, "continent": "Europe"},
  "il": {"latitude": 31.5, "longitude": 34.75, "continent": "Africa"},
  "it": {"latitude": 42.8333, "longitude": 12.8333, "continent": "Europe"},
  "ci": {"latitude": 8, "longitude": -5, "continent": "Africa"},
  "jm": {"latitude": 18.25, "longitude": -77.5, "continent": "North America"},
  "jp": {"latitude": 36, "longitude": 138, "continent": "Africa"},
  "kz": {"latitude": 48, "longitude": 68, "continent": "Africa"},
  "jo": {"latitude": 31, "longitude": 36, "continent": "Africa"},
  "ke": {"latitude": 1, "longitude": 38, "continent": "Africa"},
  "kp": {"latitude": 40, "longitude": 127, "continent": "Africa"},
  "kr": {"latitude": 37, "longitude": 127.5, "continent": "Africa"},
  "kw": {"latitude": 29.3375, "longitude": 47.6581, "continent": "Africa"},
  "kg": {"latitude": 41, "longitude": 75, "continent": "Africa"},
  "la": {"latitude": 18, "longitude": 105, "continent": "Africa"},
  "lb": {"latitude": 33.8333, "longitude": 35.8333, "continent": "Africa"},
  "ls": {"latitude": -29.5, "longitude": 28.5, "continent": "Africa"},
  "lv": {"latitude": 57, "longitude": 25, "continent": "Europe"},
  "lr": {"latitude": 6.5, "longitude": -9.5, "continent": "Africa"},
  "ly": {"latitude": 25, "longitude": 17, "continent": "Africa"},
  "li": {"latitude": 47.1667, "longitude": 9.5333, "continent": "Europe"},
  "lt": {"latitude": 56, "longitude": 24, "continent": "Europe"},
  "lu": {"latitude": 49.75, "longitude": 6.1667, "continent": "Europe"},
  "mo": {"latitude": 22.1667, "longitude": 113.55, "continent": "Africa"},
  "mg": {"latitude": -20, "longitude": 47, "continent": "Africa"},
  "mw": {"latitude": -13.5, "longitude": 34, "continent": "Africa"},
  "my": {"latitude": 2.5, "longitude": 112.5, "continent": "Africa"},
  "mv": {"latitude": 3.25, "longitude": 73, "continent": "Africa"},
  "ml": {"latitude": 17, "longitude": -4, "continent": "Africa"},
  "mt": {"latitude": 35.8333, "longitude": 14.5833, "continent": "Europe"},
  "mq": {"latitude": 14.6667, "longitude": -61, "continent": "North America"},
  "mr": {"latitude": 20, "longitude": -12, "continent": "Africa"},
  "mu": {"latitude": -20.2833, "longitude": 57.55, "continent": "Africa"},
  "mx": {"latitude": 23, "longitude": -102, "continent": "North America"},
  "mc": {"latitude": 43.7333, "longitude": 7.4, "continent": "Europe"},
  "mn": {"latitude": 46, "longitude": 105, "continent": "Africa"},
  "md": {"latitude": 47, "longitude": 29, "continent": "Europe"},
  "me": {"latitude": 42, "longitude": 19, "continent": "Europe"},
  "ms": {"latitude": 16.75, "longitude": -62.2, "continent": "North America"},
  "ma": {"latitude": 32, "longitude": -5, "continent": "Africa"},
  "mz": {"latitude": -18.25, "longitude": 35, "continent": "Africa"},
  "om": {"latitude": 21, "longitude": 57, "continent": "Africa"},
  "na": {"latitude": -22, "longitude": 17, "continent": "Africa"},
  "nr": {"latitude": -0.5333, "longitude": 166.9167, "continent": "Oceania"},
  "np": {"latitude": 28, "longitude": 84, "continent": "Africa"},
  "nl": {"latitude": 52.5, "longitude": 5.75, "continent": "Europe"},
  "an": {"latitude": 12.25, "longitude": -68.75, "continent": "North America"},
  "cw": {"latitude": 12.1833, "longitude": -68.9333, "continent": "North America"},
  "aw": {"latitude": 12.5, "longitude": -69.9667, "continent": "North America"},
  "sx": {"latitude": 18.05, "longitude": -63.08, "continent": "North America"},
  "bq": {"latitude": 17.48268, "longitude": -62.98324, "continent": "North America"},
  "nc": {"latitude": -21.5, "longitude": 165.5, "continent": "Oceania"},
  "vu": {"latitude": -16, "longitude": 167, "continent": "Oceania"},
  "nz": {"latitude": -41, "longitude": 174, "continent": "Oceania"},
  "ni": {"latitude": 13, "longitude": -85, "continent": "North America"},
  "ne": {"latitude": 16, "longitude": 8, "continent": "Africa"},
  "ng": {"latitude": 10, "longitude": 8, "continent": "Africa"},
  "nu": {"latitude": -19.0333, "longitude": -169.8667, "continent": "Oceania"},
  "nf": {"latitude": -29.0333, "longitude": 167.95, "continent": "Oceania"},
  "no": {"latitude": 62, "longitude": 10, "continent": "Europe"},
  "mp": {"latitude": 15.2, "longitude": 145.75, "continent": "Oceania"},
  "um": {"latitude": 19.2833, "longitude": 166.6, "continent": "North America"},
  "fm": {"latitude": 6.9167, "longitude": 158.25, "continent": "Oceania"},
  "mh": {"latitude": 9, "longitude": 168, "continent": "Oceania"},
  "pw": {"latitude": 7.5, "longitude": 134.5, "continent": "Oceania"},
  "pk": {"latitude": 30, "longitude": 70, "continent": "Africa"},
  "pa": {"latitude": 9, "longitude": -80, "continent": "North America"},
  "pg": {"latitude": -6, "longitude": 147, "continent": "Oceania"},
  "py": {"latitude": -23, "longitude": -58, "continent": "South America"},
  "pe": {"latitude": -10, "longitude": -76, "continent": "South America"},
  "ph": {"latitude": 13, "longitude": 122, "continent": "Africa"},
  "pn": {"latitude": -24.36146, "longitude": -128.3163761, "continent": "Oceania"},
  "pl": {"latitude": 52, "longitude": 20, "continent": "Europe"},
  "pt": {"latitude": 39.5, "longitude": -8, "continent": "Europe"},
  "gw": {"latitude": 12, "longitude": -15, "continent": "Africa"},
  "tl": {"latitude": -8.5, "longitude": 125.55, "continent": "Africa"},
  "pr": {"latitude": 18.25, "longitude": -66.5, "continent": "North America"},
  "qa": {"latitude": 25.5, "longitude": 51.25, "continent": "Africa"},
  "re": {"latitude": -21.1, "longitude": 55.6, "continent": "Africa"},
  "ro": {"latitude": 46, "longitude": 25, "continent": "Europe"},
  "ru": {"latitude": 60, "longitude": 100, "continent": "Africa"},
  "rw": {"latitude": -2, "longitude": 30, "continent": "Africa"},
  "bl": {"latitude": 17.9, "longitude": -62.8333, "continent": "North America"},
  "sh": {"latitude": -15.9333, "longitude": -5.7, "continent": "Africa"},
  "kn": {"latitude": 17.3333, "longitude": -62.75, "continent": "North America"},
  "ai": {"latitude": 18.25, "longitude": -63.1667, "continent": "North America"},
  "lc": {"latitude": 13.8833, "longitude": -61.1333, "continent": "North America"},
  "mf": {"latitude": 18.05, "longitude": -63.08, "continent": "North America"},
  "pm": {"latitude": 46.8333, "longitude": -56.3333, "continent": "North America"},
  "vc": {"latitude": 13.25, "longitude": -61.2, "continent": "North America"},
  "sm": {"latitude": 43.7667, "longitude": 12.4167, "continent": "Europe"},
  "st": {"latitude": 1, "longitude": 7, "continent": "Africa"},
  "sa": {"latitude": 25, "longitude": 45, "continent": "Africa"},
  "sn": {"latitude": 14, "longitude": -14, "continent": "Africa"},
  "rs": {"latitude": 44, "longitude": 21, "continent": "Europe"},
  "sc": {"latitude": -4.5833, "longitude": 55.6667, "continent": "Africa"},
  "sl": {"latitude": 8.5, "longitude": -11.5, "continent": "Africa"},
  "sg": {"latitude": 1.3667, "longitude": 103.8, "continent": "Africa"},
  "sk": {"latitude": 48.6667, "longitude": 19.5, "continent": "Europe"},
  "vn": {"latitude": 16, "longitude": 106, "continent": "Africa"},
  "si": {"latitude": 46, "longitude": 15, "continent": "Europe"},
  "so": {"latitude": 10, "longitude": 49, "continent": "Africa"},
  "za": {"latitude": -29, "longitude": 24, "continent": "Africa"},
  "zw": {"latitude": -20, "longitude": 30, "continent": "Africa"},
  "es": {"latitude": 40, "longitude": -4, "continent": "Europe"},
  "ss": {"latitude": 4.85, "longitude": 31.6, "continent": "Africa"},
  "eh": {"latitude": 24.5, "longitude": -13, "continent": "Africa"},
  "sd": {"latitude": 15, "longitude": 30, "continent": "Africa"},
  "sr": {"latitude": 4, "longitude": -56, "continent": "South America"},
  "sj": {"latitude": 78, "longitude": 20, "continent": "Europe"},
  "sz": {"latitude": -26.5, "longitude": 31.5, "continent": "Africa"},
  "se": {"latitude": 62, "longitude": 15, "continent": "Europe"},
  "ch": {"latitude": 47, "longitude": 8, "continent": "Europe"},
  "sy": {"latitude": 35, "longitude": 38, "continent": "Africa"},
  "tj": {"latitude": 39, "longitude": 71, "continent": "Africa"},
  "th": {"latitude": 15, "longitude": 100, "continent": "Africa"},
  "tg": {"latitude": 8, "longitude": 1.1667, "continent": "Africa"},
  "tk": {"latitude": -9, "longitude": -172, "continent": "Oceania"},
  "to": {"latitude": -20, "longitude": -175, "continent": "Oceania"},
  "tt": {"latitude": 11, "longitude": -61, "continent": "North America"},
  "ae": {"latitude": 24, "longitude": 54, "continent": "Africa"},
  "tn": {"latitude": 34, "longitude": 9, "continent": "Africa"},
  "tr": {"latitude": 39, "longitude": 35, "continent": "Africa"},
  "tm": {"latitude": 40, "longitude": 60, "continent": "Africa"},
  "tc": {"latitude": 21.75, "longitude": -71.5833, "continent": "North America"},
  "tv": {"latitude": -8, "longitude": 178, "continent": "Oceania"},
  "ug": {"latitude": 1, "longitude": 32, "continent": "Africa"},
  "ua": {"latitude": 49, "longitude": 32, "continent": "Europe"},
  "mk": {"latitude": 41.8333, "longitude": 22, "continent": "Europe"},
  "eg": {"latitude": 27, "longitude": 30, "continent": "Africa"},
  "gb": {"latitude": 54, "longitude": -2, "continent": "Europe"},
  "gg": {"latitude": 49.45, "longitude": -2.58, "continent": "Europe"},
  "je": {"latitude": 49.2167, "longitude": -2.1167, "continent": "Europe"},
  "im": {"latitude": 54.23, "longitude": -4.57, "continent": "Europe"},
  "tz": {"latitude": -6, "longitude": 35, "continent": "Africa"},
  "us": {"latitude": 38, "longitude": -97, "continent": "North America"},
  "vi": {"latitude": 18.3333, "longitude": -64.8333, "continent": "North America"},
  "bf": {"latitude": 13, "longitude": -2, "continent": "Africa"},
  "uy": {"latitude": -33, "longitude": -56, "continent": "South America"},
  "uz": {"latitude": 41, "longitude": 64, "continent": "Africa"},
  "ve": {"latitude": 8, "longitude": -66, "continent": "South America"},
  "wf": {"latitude": -13.3, "longitude": -176.2, "continent": "Oceania"},
  "ws": {"latitude": -13.5833, "longitude": -172.3333, "continent": "Oceania"},
  "ye": {"latitude": 15, "longitude": 48, "continent": "Africa"},
  "zm": {"latitude": -15, "longitude": 30, "continent": "Africa"},
  "xs": {"latitude": 10.1813335, "longitude": 114.365081799, "continent": "A"
  }
}



for (var i=0; i<countries.length; i++) {
  var entry = countries[i];
  var code = entry['cca2'];
  var lowercode = code.toLowerCase();
  if (code && code.length > 0 && lowercode && lowercode.length > 0 && data.country[lowercode]) {
    var new_country = {
      countryCode:  code,
      countryName:  (entry['name']         && entry['name'].length         > 0) ? entry['name']         : undefined,
      currency:     (entry['currency']     && entry['currency'].length     > 0) ? entry['currency']     : undefined,
      continent:    (entry['region']       && entry['region'].length       > 0) ? entry['region']       : undefined,
      subContinent: (entry['subregion']    && entry['subregion'].length    > 0) ? entry['subregion']    : undefined,
      phoneCode:    (entry['calling-code'] && entry['calling-code'].length > 0) ? entry['calling-code'] : undefined,
      latitude:     data.country[lowercode].latitude,
      longitude:    data.country[lowercode].longitude
    }
    data.country[lowercode] = new_country;
  } else {
    console.log(lowercode + ' not in data.country');
  }
}


data.state = {
	"AK": {"latitude": 61.3850, "longitude": -152.2683},
	"AL": {"latitude": 32.7990, "longitude": -86.8073},
	"AR": {"latitude": 34.9513, "longitude": -92.3809},
	"AS": {"latitude": 14.2417, "longitude": -170.7197},
	"AZ": {"latitude": 33.7712, "longitude": -111.3877},
	"CA": {"latitude": 36.1700, "longitude": -119.7462},
	"CO": {"latitude": 39.0646, "longitude": -105.3272},
	"CT": {"latitude": 41.5834, "longitude": -72.7622},
	"DC": {"latitude": 38.8964, "longitude": -77.0262},
	"DE": {"latitude": 39.3498, "longitude": -75.5148},
	"FL": {"latitude": 27.8333, "longitude": -81.7170},
	"GA": {"latitude": 32.9866, "longitude": -83.6487},
	"HI": {"latitude": 21.1098, "longitude": -157.5311},
	"IA": {"latitude": 42.0046, "longitude": -93.2140},
	"ID": {"latitude": 44.2394, "longitude": -114.5103},
	"IL": {"latitude": 40.3363, "longitude": -89.0022},
	"IN": {"latitude": 39.8647, "longitude": -86.2604},
	"KS": {"latitude": 38.5111, "longitude": -96.8005},
	"KY": {"latitude": 37.6690, "longitude": -84.6514},
	"LA": {"latitude": 31.1801, "longitude": -91.8749},
	"MA": {"latitude": 42.2373, "longitude": -71.5314},
	"MD": {"latitude": 39.0724, "longitude": -76.7902},
	"ME": {"latitude": 44.6074, "longitude": -69.3977},
	"MI": {"latitude": 43.3504, "longitude": -84.5603},
	"MN": {"latitude": 45.7326, "longitude": -93.9196},
	"MO": {"latitude": 38.4623, "longitude": -92.3020},
	"MP": {"latitude": 14.8058, "longitude": -145.5505},
	"MS": {"latitude": 32.7673, "longitude": -89.6812},
	"MT": {"latitude": 46.9048, "longitude": -110.3261},
	"NC": {"latitude": 35.6411, "longitude": -79.8431},
	"ND": {"latitude": 47.5362, "longitude": -99.7930},
	"NE": {"latitude": 41.1289, "longitude": -98.2883},
	"NH": {"latitude": 43.4108, "longitude": -71.5653},
	"NJ": {"latitude": 40.3140, "longitude": -74.5089},
	"NM": {"latitude": 34.8375, "longitude": -106.2371},
	"NV": {"latitude": 38.4199, "longitude": -117.1219},
	"NY": {"latitude": 42.1497, "longitude": -74.9384},
	"OH": {"latitude": 40.3736, "longitude": -82.7755},
	"OK": {"latitude": 35.5376, "longitude": -96.9247},
	"OR": {"latitude": 44.5672, "longitude": -122.1269},
	"PA": {"latitude": 40.5773, "longitude": -77.2640},
	"PR": {"latitude": 18.2766, "longitude": -66.3350},
	"RI": {"latitude": 41.6772, "longitude": -71.5101},
	"SC": {"latitude": 33.8191, "longitude": -80.9066},
	"SD": {"latitude": 44.2853, "longitude": -99.4632},
	"TN": {"latitude": 35.7449, "longitude": -86.7489},
	"TX": {"latitude": 31.1060, "longitude": -97.6475},
	"UT": {"latitude": 40.1135, "longitude": -111.8535},
	"VA": {"latitude": 37.7680, "longitude": -78.2057},
	"VI": {"latitude": 18.0001, "longitude": -64.8199},
	"VT": {"latitude": 44.0407, "longitude": -72.7093},
	"WA": {"latitude": 47.3917, "longitude": -121.5708},
	"WI": {"latitude": 44.2563, "longitude": -89.6385},
	"WV": {"latitude": 38.4680, "longitude": -80.9696},
	"WY": {"latitude": 42.7475, "longitude": -107.2085}
}



function country(code)
{
	code = (code) ? code.toLowerCase() : '';
	return data.country[code];
}



function state(code)
{
	code = (code) ? code.toUpperCase() : '';
	return data.state[code];
}



module.exports.country = country;
module.exports.state = state;
